### ISSUE TITLE
Add civilians to groupData

### ISSUE THREAD

**Issue by shadow-fa** [folkarps/F3#248]
Since we have a civilian briefing we should also add civilians to:
`groupMarkers/fn_groupData.sqf` and `groupMarkers/f_setLocalGroupMarkers.sqf`.
This will make it easier for missionmakers to add civilian slots.

**Comment by NikkoJT** [comment]
Include the reporters in this by default, so there's no need for the role text matching workaround in setGroupIDs.

**Comment by shadow-fa** [comment]
Thereporter text matching exists so that upgraded missions (from older f3 versions) wouldnt throw an error.
This is because previously reporter slots didn't have a group ID/variable.

If other slots (such as zeus and spectator) wouldnt work either, when taken from an older mission, then we could simply remove this workaround and demand that these slots be taken from the current version.

**Comment by NikkoJT** [comment]
I don't know about older missions, but the current reporters have no group ID assigned and will cause errors if their role text is changed.

So they should be included in groupData anyway.

**Comment by shadow-fa** [comment]
You're right.
I should clarify: By `group ID/variable.` I meant the variable names for the groups that are set in the editor. e.g. `GrpFIA_IFV2`.

**Comment by SamLex** [comment]
Reporters are probably going away at some point (#195). I'm also curious about the usecase there. I don't recall the civilian briefing being used before (I might be wrong here). It does seem unlikely for there to be player civilians due to the way AI treats civilian unis. So maybe a better approach would be to exclude civilians from these components instead?

**Comment by NikkoJT** [comment]
The original reason I brought this up, is that the groupID component generates an error if any playable group doesn't have a callsign set in F3. This includes civilian groups, but there's no way to set an F3 callsign for civilian groups by default. That creates a scenario where the missionmaker can do something very ordinary (placing a playable unit) and end up having to rewire F3 components to make it work properly.

While civilian units are not used often, I think it would be better to allow for that possibility, particularly since the effort required is very small - one additional case in groupData and setLocalGroupMarkers, and a mostly empty case at that.

**Comment by shadow-fa** [comment]
>I'm also curious about the usecase there

Afterparty missions use civilians a lot.

**Comment by SamLex** [comment]
Tested by slotting BBC Reporter in template. Reporters had markers as expected.
