### ISSUE TITLE
Dynamic Briefing

### ISSUE THREAD

**Issue by shadow-fa** [folkarps/F3#269]
Now that we have this <https://community.bistudio.com/wiki/setDiaryRecordText> (soon),
do we want to update our briefing pages dynamically (ORBAT, Loadout, etc) ?
E.g. ORBAT could show JIP players or remove groups that have died.

**Comment by SamLex** [comment]
Personally I quite like that the ORBAT is static; lets you see how was what rather than how is what and avoid 'metagaming' (although delaying ups mitigates that but that then gets messy).

I think loadout and loadout group are _more_ open to being updated but not too sure.

I think having it better support JIP players would be good though, having the AI name replaced with the human name, even in the ORBAT. Could end up with players listed twice in the case of reinforcements though.

I could be persuaded on this but definitely needs very wide discussion.

**Comment by NikkoJT** [comment]
I'm not sure this is particularly necessary. ORBAT indicating the initial ORBAT rather than being live seems perfectly fine to me. The Loadout tab is essentially replaced by the in-game inventory after the mission starts, and manually keeping track of what resources people actually have is part of the logistics & cooperation game, not something I'd like to automate.

Fixing JIP names is about the only moderately-interesting possibility I see here, but we don't have a huge amount of trouble with it anyway and trying to implement a solution may be more trouble than it's worth.

**Comment by costno** [comment]
I agree with Nikko, consider closing this.

**Comment by SamLex** [comment]
Agreed, closing
