### ISSUE TITLE
Find a way to make CasCap work with reinforcements

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#329]
I want to find a way to force CasCap to update its array with newly-joined players (reinforcements) when operating in playable units mode. This is probably going to be a bit complicated, but I think it's worth it to resolve the problem where the mission can be ended early by CasCap if all the initial slots die.

**Comment by NikkoJT** [comment]
Using the merged version of this file, enabling a default SIDE 100 cascap setting causes this error:

```
3:01:25 Error in expression < _collectSideGroups;
};


_remaining = {alive _x} count (_grps apply {units _x})>
 3:01:25   Error position: <alive _x} count (_grps apply {units _x})>
 3:01:25   Error alive: Type Array, expected Object
(line 125)
```

**Comment by NikkoJT** [comment]
`flatten` would probably do it

**Comment by SamLex** [comment]
Ah, yeah, that does it, forgot about that.

Seems that fixes the script error by adding `flatten` around the `_grps apply`. The same needs to be done for `_started`. Will raise a PR later tonight

**Comment by SamLex** [comment]
JIP didn't stop CasCap from triggering in formal testing so there is still an issue. Debug logging also doesn't work because `player` is undefined on a dedicated server, so hard to know exactly what is going on. First change is to change debug logs to `systemChat` so they appear in the server log.

I suspect that the `leader _x in playableUnits` check here is causing an issue if the group leader is killed. I think it momentarily causes the group to not be eligible and if the check runs in that moment CasCap will trigger as if the whole group was killed. 
https://github.com/folkarps/F3/blob/692c1007c2ae2f6d20cb6648e2332a631164bd1e/f/casualtiesCap/f_CasualtiesCapCheck.sqf#L65
