### ISSUE TITLE
Change groupMarkers to use type instead of variable name to determine unit vs group

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#333]
Currently f_setLocalGroupMarkers.sqf checks the passed object's variable name to see if it contains "Unit" when determining whether it gets a group marker or a specialist unit marker. This makes it unintuitive to create specialist markers for non-template units, especially since the check is case-sensitive.

This should be changed to check whether the passed object is typeOf "Man" (or something similar).

**Comment by shadow-fa** [comment]
This complicates things a bit as we also have to move this loop here and spawn it for each marker:
https://github.com/folkarps/F3/blob/fa70671af348040c4e3114eb7842d1e90c3f7cc7/f/groupMarkers/fn_localGroupMarker.sqf#L20-L29
This is, because we first have to wait for the object to exist (and make sure not to use `grpNull` as the default value in `missionNamespace getVariable ...`), before we can check if it's a group or not.
It's probably a good idea to use something like this
```sqf
private _obj = missionNamespace getVariable [_group,objNull];
if (_obj isEqualType grpNull) ...
```
