### ISSUE TITLE
Investigate possible problem with Zeus slots not allowing objects to be placed

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#342]
https://discord.com/channels/101479298812121088/277196621908017162/833464791346446336

Investigation is underway. Still unclear whether this can be resolved F3-side, will update with further news.

**Comment by NikkoJT** [comment]
Initial testing strongly suggests that the problem is located in f_fnc_zeusAddAddons.sqf.

If nothing in that file is actually required, my preliminary recommendation is to drop that function and instead use the editor zeus module attributes to allow all addons.

**Comment by NikkoJT** [comment]
Further testing has confirmed that the problem is located in f_fnc_zeusAddAddons.sqf.

That file does exactly 2 things, both of which can be done in the editor, so in the interests of making Zeus usable again the expedient plan appears to be to do that.

**Comment by SamLex** [comment]
I've been out of this for far too long and not experienced this issue personally so not wanting to interfere, but wanted to share some finding for a dig into this today.

The Zeus module initialisation function uses nearly identical code to f_fnc_zeusAddAddons.sqf for "all addons including unofficial ones". And in local testing the results of `curatorAddons` and `activedAddons` are the same with the module dropdown set + the script commented out and f_fnc_zeusAddAddons.sqf.
![image](https://user-images.githubusercontent.com/733683/116897713-7fa5a500-ac2d-11eb-9694-0b770b030c8a.png)

f_fnc_zeusAddAddons.sqf however does set the "Addons" variable that is used by the module initialisation code. It is also called from f_fnc_zeusInit.sqf with `spawn`. Further, since f_fnc_zeusInit.sqf is run from the object initialisation field of the Zeus/Curator modules it is run _before_ the module itself is initialised as per [Initialisation Order](https://community.bistudio.com/wiki/Initialization_Order).

This leads to the possibility that f_fnc_zeusAddAddons.sqf and the module initialisation run at the same time, and interfere with each other in weird ways.

My suggestion would be to change f_fnc_zeusAddAddons.sqf to work with the module initialisation, rather than duplicate its behaviour, and change how f_fnc_zeusAddAddons is called to ensure it runs _before_ the module initialisation. Something like:

Change these to `call`
https://github.com/folkarps/F3/blob/6cfc36d8fd43bdc131216d63220e28f03c9e782c/f/zeus/fn_zeusInit.sqf#L73-L76

Remove this line since it overrides the module dropdown in the ARRAY and STRING cases
https://github.com/folkarps/F3/blob/6cfc36d8fd43bdc131216d63220e28f03c9e782c/f/zeus/fn_zeusAddAddons.sqf#L44

Change these to **only** set the Addons variable. This is equivalent to setting the dropdown in the module
https://github.com/folkarps/F3/blob/6cfc36d8fd43bdc131216d63220e28f03c9e782c/f/zeus/fn_zeusAddAddons.sqf#L50-L63


These changes should have the same effect as changing the module dropdown to "all addons including unofficial" but is done in code which helps with updating older missions. We could also change the template to have that dropdown set by default to be extra sure.

**Comment by NikkoJT** [comment]
Thanks for the input, Lexer. I will arrange for your possible fix to be tested next session.

**Comment by SamLex** [comment]
Thanks Nikko. I plan to attend session again myself soon, but probably best if this is tested by someone familiar with the issue.

I can raise a PR with this fix if it seems to be working

**Comment by NikkoJT** [comment]
Resolved in 3.5.6; #348 remains active.
