### ISSUE TITLE
Change group markers to 'average' location

### ISSUE THREAD

**Issue by SamLex** [folkarps/F3#47]
(Pre-assumption: the intent of group markers is to allow command elements to easily see the rough location of elements)

Currently group markers follow the leader of a group, which works fine if the FT are all near the leader and the leader of the group after a loss is correct. It breaks down somewhat during bounding maneuvers, when a FT becomes seperated and when the A3 rank system fails to choose the correct new leader.

I propose having the markers follow the 'average' location of all members of the FT. This would give a more general location of the FT, and remove the dependance on the group leader being correct.

An alternative could be as above, but add in FTL markers similar to medic markers. This way the location of the leader could also be seen in addition to the general FT location. This could, however, lead to too much map clutter.

**Comment by shadow-fa** [comment]
The newly proposed group marker system in #69 might/will resolve some of the issues with the previous group markers. I think that we should implement #69 instead of this.

**Comment by shadow-fa** [comment]
```
If the only issue is incorrect markers due to dead leaders, 
I would propose that we instead check for and remove dead leaders from the group.
```
This however allows for the death of the team leader to be "communicated" early to team members as well as other teams.

**Comment by NikkoJT** [comment]
Group leaders are already _sometimes_ removed immediately, it's just inconsistent because BI (sometimes they are _never_ removed). I'd prefer to make it consistent. If "early information" is likely to be a real issue then our solution could include a delay before removing them.

Personally I would prefer to stick with the marker being on the team leader. There are a few reasons for this:

1. It's the only way to tell which group member marker is the leader without STUI.
2. It provides a consistent known position for the team leader to reference ("request medic on A1 marker").
3. In scenarios where I am trying to physically locate the group, as a unit outside the group, I would prefer to be able to find at least the team leader rather than being guided to an empty position midway between their split elements.
4. It can't be made inaccurate by one team member being AFK or something.
5. Philosophically, I would like to give the team leader authority over the group's official position.
6. It's consistent with vanilla behaviour i.e. in the Editor and Zeus.

**Comment by SamLex** [comment]
Discussion from Discord regarding this and #43 
https://discordapp.com/channels/101479298812121088/277196621908017162/553315038354604043

**Comment by SamLex** [comment]
Good points @NikkoJT, I agree. Closing this issue in favour of #227
